name: Deploy backend

on:
  push:
    branches: [ main, f* ]

env:
  AWS_REGION: us-east-1
  AWS_BUCKET: hangarteam1-bucket
  AWS_EC2_METADATA_DISABLED: true

jobs:

  deploy:
    name: "Deploy to aws"
    runs-on: ubuntu-22.04
    permissions:
      id-token: write
      contents: read
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Include secrets # Esta técnica solo para casos simples
        run: |
          echo "JWT_SECRET = "${{ secrets.JWT_SECRET }} >> .env
          echo "DB_CONNECTION_STRING = "${{ secrets.DB_CONNECTION_STRING }} >> .env

      - name: Setup NodeJs
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies and build
        run: |
          yarn i
          yarn build
          zip -rq package.zip .
          du -hs package.zip
    
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_GITHUB_ROLE }}
          aws-region: ${{ env.AWS_REGION }}
      
      - name: Upload package to aws bucket
        run: |
          aws s3 cp --quiet ./package.zip s3://$AWS_BUCKET/package-$GITHUB_SHA.zip
      
      - name: Deploy stack to Cloudformation
        run: |
          aws cloudformation deploy \
            --stack-name HangarTeam1Twitter \
            --template-file ./deployment/stack.yml \
            --parameter-overrides \
              LambdaCodeS3Bucket=${{ env.AWS_BUCKET }} \
              LambdaCodeS3Key=package-$GITHUB_SHA.zip \
            --capabilities CAPABILITY_IAM
